create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  stripe_session_id text not null unique,
  payment_intent_id text,
  status text not null default 'new' check (status in ('new', 'preparing', 'shipped', 'delivered', 'cancelled')),
  payment_status text not null,
  amount_total integer not null,
  currency text not null,
  customer_name text,
  customer_email text,
  customer_phone text,
  billing_address jsonb,
  shipping_address jsonb,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;
