import { TL_ONLY_DISPLAY, DOMESTIC_SHIPPING_FEE } from '../shared/pricing.js';
const shippingFeeText = new Intl.NumberFormat('tr-TR').format(DOMESTIC_SHIPPING_FEE / 100) + ' TL';
// Public policies describe current services; operational compliance is tracked separately.
export const legalLabels = {
  tr: { terms: "Mesafeli Satış Sözleşmesi", returns: "Teslimat ve İade Şartları", privacy: "Gizlilik Sözleşmesi / KVKK" },
  en: { terms: "Distance Sales Agreement", returns: "Delivery & Returns", privacy: "Privacy / KVKK" },
  de: { terms: "Fernabsatzvertrag", returns: "Lieferung & Rückgabe", privacy: "Datenschutz / KVKK" },
  sv: { terms: "Distansköpsavtal", returns: "Leverans & returer", privacy: "Integritet / KVKK" }
};

export const legalLanguageNotes = {
  tr: "Türkiye satışları için Türkçe metin · 22 Eylül 2026",
  en: "Turkish-language document for sales in Türkiye · 22 September 2026",
  de: "Türkischsprachiges Dokument für Verkäufe in der Türkei · 22. September 2026",
  sv: "Dokument på turkiska för försäljning i Turkiet · 22 september 2026"
};

const care = '<a href="mailto:contact@dagdroom.de">contact@dagdroom.de</a>';
const privacy = '<a href="mailto:contact@dagdroom.de">contact@dagdroom.de</a>';
const businessAddress = '1821/1 Sokak 7/9 Bostanlı Karşıyaka / İZMİR';
const identity = `Marka: Dagdroøm. Satıcı / veri sorumlusu: Barış Türkmen (şahıs işletmesi). Açık adres: ${businessAddress}. Vergi dairesi: Çiğli Vergi Dairesi. Vergi numarası: 8790693184. Telefon: <a href="tel:+905389715733">0538 971 57 33</a>. MERSİS numarası bulunmamaktadır. KEP adresi: <a href="mailto:baris.turkmen@hs01.kep.tr">baris.turkmen@hs01.kep.tr</a>.`;

export const legalPages = {
  "/terms": {
    title: legalLabels.tr.terms,
    intro: "Dagdroøm üzerinden Türkiye içindeki tüketicilere yapılan çevrim içi ürün satışlarına ilişkin genel sözleşme koşullarıdır. Online ödeme, iyzico başvurusu ve teknik entegrasyon tamamlandıktan sonra açılacaktır.",
    sections: [
      ["01 · Taraflar", `${identity} Sipariş desteği: ${care}. Alıcı; adı, iletişim ve teslimat bilgileri siparişte yer alan tüketicidir.`],
      ["02 · Konu ve sipariş bilgileri", "Sözleşme, seçilen giyim ürününün satışı ve teslimini kapsar. Online satış açıldığında ürün, beden, renk, adet, vergili bedel, kargo ücreti, toplam tutar, ödeme şekli ve teslimat koşullarının siparişe özgü ön bilgilendirmede sunulması; sipariş onayının ödeme yükümlülüğü doğurduğunun açıkça belirtilmesi gerekir. Bu genel sayfa, siparişe özgü ön bilgilendirme ve sözleşme nüshasının yerine geçmez."],
      ["03 · Ödeme ve teslimat", "Siparişler, ödeme onayından itibaren en geç 2 iş günü içinde Yurtiçi Kargo’ya teslim edilir. Bu süre kargoya verme süresidir; müşteriye teslim süresi değildir. Ürün fiyatları KDV dahil, kargo hariçtir. Türkiye içi siparişlerde KDV dahil " + shippingFeeText + " sabit kargo bedeli sipariş başına bir kez eklenir; ürün tutarı, kargo bedeli ve ödenecek toplam sepette ayrı gösterilir. Teslimat, bildirilen süre içinde ve kişiye özel üretim istisnası dışında en geç 30 günde yapılır. Önceden açıklanmayan ek ücretler tüketiciye yüklenemez. Satıcının belirttiği taşıyıcıyla teslimata kadar kayıp ve hasar sorumluluğu satıcıdadır."],
      ["04 · Cayma ve geri ödeme", 'Cayma bildirimi, geri gönderim, kargo masrafları ve geri ödeme koşulları <a href="/shipping-returns">Teslimat ve İade Şartları</a> sayfasında açıklanmıştır; bu koşullar sözleşmenin parçasıdır.'],
      ["Teslimatın imkânsızlaşması", "Siparişin yerine getirilmesi imkânsızlaşırsa bu durum öğrenildiği tarihten itibaren 3 gün içinde yazılı olarak veya kalıcı veri saklayıcısıyla bildirilir. Tahsil edilmiş tutarlar, teslimat giderleri dahil, bildirimden itibaren en geç 14 gün içinde iade edilir. Ürünün stokta bulunmaması tek başına imkânsızlık sayılmaz."],
      ["05 · Ayıplı ürünler", "Ürün kararlaştırılan nitelikleri taşımıyorsa tüketici, kanuni koşulları çerçevesinde sözleşmeden dönme, bedel indirimi, ücretsiz onarım veya ayıpsız ürünle değişim haklarından yararlanabilir. Bu haklar, gerekçesiz cayma süresiyle sınırlandırılamaz."],
      ["06 · Başvurular ve kapsam", `Satış ve teslimat kapsamı Türkiye ile sınırlıdır. Siparişe ilişkin talepler ${care} üzerinden iletilebilir. Tüketicinin yetkili tüketici hakem heyetine veya tüketici mahkemesine başvuru hakkı saklıdır.`]
    ]
  },
  "/shipping-returns": {
    title: legalLabels.tr.returns,
    intro: "Siparişler, ödeme onayından itibaren en geç 2 iş günü içinde Yurtiçi Kargo’ya teslim edilir. Bu süre kargoya verme süresidir; müşteriye teslim süresi değildir. Ürün fiyatları KDV dahil, kargo hariçtir. Türkiye içi siparişlerde KDV dahil " + shippingFeeText + " sabit kargo bedeli sipariş başına bir kez eklenir; ürün tutarı, kargo bedeli ve ödenecek toplam sepette ayrı gösterilir. İade talebiniz için müşteri hizmetleriyle iletişime geçebilirsiniz.",
    sections: [
      ["Teslimat kapsamı ve süresi", "Teslimat yalnızca Türkiye içindeki adreslere yapılır. Kargoya verildikten sonra teslimat süresi adrese ve taşıyıcının dağıtım planına göre değişebilir. Taahhüt edilen teslimat süresi saklı kalmak üzere, kişiye özel üretim istisnası dışında teslimat en geç 30 gün içinde tamamlanır. Teslimatla ilgili sorularınız için contact@dagdroom.de adresine yazabilirsiniz."],
      ["01 · Cayma hakkı", `Teslimden itibaren 14 gün içinde gerekçesiz ve cezasız cayabilirsiniz; teslimden önce de cayma mümkündür. Açık cayma bildiriminizi ${care} adresine iletebilirsiniz. Bildirimin geçerliliği müşteri hizmetlerinin onayına bağlı değildir.`],
      ["02 · Ürünü gönderme", `Cayma bildiriminden itibaren 14 gün içinde ürünü geri gönderin. İade alıcısı: Barış Türkmen. İade adresi: ${businessAddress}. İade taşıyıcısı: Yurtiçi Kargo. Belirtilen taşıyıcıyla iadede masraf alınmaz; taşıyıcı belirtilmemişse de iade masrafı tüketiciye yüklenemez. Gönderi belgesini saklayın.`],
      ["03 · Bedel iadesi", "Teslimat giderleri dahil geri ödeme, belirtilen taşıyıcıya teslimden; başka taşıyıcı kullanılırsa ürünün satıcıya ulaşmasından itibaren 14 gün içinde yapılır. Teslim öncesi caymada süre bildirimle başlar. İade, kullanılan ödeme aracına uygun biçimde, tek seferde ve masrafsız yapılır."],
      ["04 · Ürün durumu ve istisnalar", "Tüketici ALICI’nın cayma hakkını kullandığına ilişkin bildirimi yönelttiği tarihten itibaren 14 (on dört) gün içinde malı SATICI’ya geri göndermesi gerekmektedir. İadeye konu mal ile beraber söz konusu malın faturasının, kutusunun, ambalajının, varsa standart aksesuarlarının ve söz konusu malın satın alınması sebebiyle hediye edilen diğer ürünlerin de eksiksiz ve hasarsız olarak SATICI’ya iade edilmesi gerekmektedir. Tüketici ALICI, cayma süresi içinde malı, işleyişine, teknik özelliklerine ve kullanım talimatlarına uygun bir şekilde kullanmalıdır, aksi halde malda meydana gelen değişiklik ve bozulmalardan sorumludur.<br><br>Kişiye özel hazırlanan ürünler ile koruyucu ambalajı açılmış, sağlık veya hijyen nedeniyle iadeye uygun olmayan ürünlerde kanuni istisnalar uygulanabilir. Her pijama veya giyim ürünü otomatik olarak hijyen istisnasına girmez."],
      ["05 · Değişim ve kusurlu ürün", `Beden veya renk tercihi nedeniyle doğrudan değişim yapılmamaktadır. Farklı bir beden veya renk isterseniz mevcut ürünü cayma hakkı ve bu sayfadaki iade koşulları kapsamında iade edebilir, istediğiniz ürün için stok durumuna göre yeni sipariş oluşturabilirsiniz. Yeni sipariş, verildiği tarihteki ürün fiyatı ve kargo koşullarına tabidir. İade bedeli yeni siparişten bağımsız olarak yukarıda belirtilen süre ve yöntemle geri ödenir; yeniden alışveriş yapmanız zorunlu değildir. Destek için ${care} adresine yazabilirsiniz. Kusurlu ya da yanlış ürün tesliminde, kanuni koşulları kapsamında ayıpsız ürünle değişim dahil seçimlik haklarınız korunur; bu durumlarda yeni sipariş vermeniz şart koşulmaz. Fotoğraf paylaşmanız incelemeyi kolaylaştırabilir, hak kullanımı yalnızca fotoğraf sunulmasına bağlanmaz.`],
      ["06 · Örnek cayma bildirimi", "Alıcı adı soyadı: … / Sipariş numarası: … / Ürün: … / Sipariş ve teslim tarihi: … / Adres: … / Bildirim tarihi: … — Belirttiğim ürünün satışına ilişkin sözleşmeden cayma hakkımı kullanıyorum. Bu örneği kullanmak zorunlu değildir; açık bir cayma beyanı yeterlidir."]
    ]
  },
  "/privacy": {
    title: legalLabels.tr.privacy,
    intro: "Bu Gizlilik ve Kişisel Verilerin Korunması Politikası, Dagdroøm internet sitesini ziyaret eden, bizimle iletişime geçen ve alışveriş yapan kişilere yönelik veri işleme esaslarını açıklar. 6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) kapsamında aydınlatma amacı taşır; bu sayfayı okumak veya siteyi kullanmak pazarlama izni ya da açık rıza verilmesi anlamına gelmez.",
    sections: [
      ["01 · Veri sorumlusu ve iletişim", `${identity} E-posta: ${privacy}. Kişisel verilerinizle ilgili sorularınızı ve taleplerinizi bu iletişim kanallarından iletebilirsiniz.`],
      ["02 · Toplanan bilgiler ve yöntem", "Siteye erişirken IP adresi, tarayıcı ve cihaz bilgisi, erişim zamanı ve istek kayıtları gibi teknik bilgiler barındırma altyapısına ulaşabilir. Bize yazdığınızda adınız, e-posta adresiniz, mesajınız ve gönderdiğiniz ekler işlenir. Alışveriş işlemlerinde ad soyad, telefon, e-posta, teslimat ve fatura adresi, ürün, adet, tutar, işlem referansı ve sipariş/ödeme durumu bilgileri kullanılabilir. Bilgiler elektronik ortamda doğrudan sizden, tarayıcı isteklerinden ve hizmet sağlayıcılarının işlem bildirimlerinden elde edilir. İletişim formu kendi e-posta uygulamanızı açar; mesaj ancak sizin göndermenizle iletilir. Mevcut üyelik ve bülten formları hesap veya abonelik kaydı oluşturmamakta, girilen bilgileri bu amaçlarla sunucuya göndermemektedir."],
      ["03 · İşleme amaçları ve hukuki sebepler", "Ürün ve sipariş taleplerini yanıtlamak, satış işlemlerini yürütmek ve teslimatı sağlamak için gerekli veriler sözleşmenin kurulması veya ifası kapsamında (KVKK 5/2-c); faturalama ve zorunlu kayıtlar hukuki yükümlülükler kapsamında (5/2-ç); şikâyet, iade ve uyuşmazlık kayıtları bir hakkın tesisi, kullanılması veya korunması kapsamında (5/2-e) işlenir. Site güvenliği ve hizmetin çalışması için gerekli teknik işlemlerde, temel hak ve özgürlüklerinize zarar vermemek kaydıyla meşru menfaat (5/2-f) esas alınır. Ayrı bir izin gerektiren pazarlama faaliyeti bu metne dayanılarak başlatılmaz."],
      ["04 · Bilgilerin paylaşıldığı taraflar", 'Site Vercel üzerinden yayımlanır; ziyaretçi istekleri bu barındırma altyapısınca işlenir. İletişim e-postası GoDaddy E-posta Başlangıç hizmetini kullanır; yazışma ve ekleri e-posta hizmeti üzerinden iletilir ve tutulur. KEP yazışmaları KEP hizmet sağlayıcısı üzerinden yürütülür. Satış açıldığında ödeme işlemleri için seçilen sağlayıcı iyzico’dur (iyzi Ödeme ve Elektronik Para Hizmetleri A.Ş.); ödeme işlemi için gerekli sipariş, tutar, iletişim ve fatura bilgileri bu sağlayıcıyla paylaşılır. <a href="https://www.iyzico.com/gizlilik-politikasi" target="_blank" rel="noopener noreferrer">iyzico gizlilik politikası</a> kendi hizmetindeki işlemleri açıklar. Teslimatta gerekli alıcı, adres ve telefon bilgileri Yurtiçi Kargo’ya; yasal yükümlülükler kapsamında gerekli kayıtlar yetkili kurumlara iletilebilir. Ödeme entegrasyonu tamamlanana kadar sitede online ödeme kapalıdır.'],
      ["05 · Yurt dışındaki hizmet altyapıları", 'Barındırma ve e-posta hizmetlerinin yurt dışındaki sistemleri kullanması nedeniyle, teknik erişim kayıtları ve e-posta yazışmaları Türkiye dışında işlenebilir. Bu nedenle Türkiye içi satış yapılması, tüm kişisel verilerin yalnızca Türkiye’de tutulduğu anlamına gelmez. Hizmet sağlayıcılarının işleme düzenlerine ilişkin bilgiler <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Vercel</a> ve <a href="https://www.godaddy.com/en/agreements/privacy" target="_blank" rel="noopener noreferrer">GoDaddy</a> politikalarında yer alır. Yurt dışı aktarımlar bakımından KVKK 9’da öngörülen şartların ve uygulanabilir güvencelerin sağlanması gerekir. Bu aydınlatma metni bir aktarım izni, açık rıza veya standart sözleşme yerine geçmez. Aktarım işlemleri hakkındaki bilgi taleplerinizi iletişim adreslerimize iletebilirsiniz.'],
      ["06 · Çerezler ve tarayıcı depolaması", (TL_ONLY_DISPLAY ? 'Site dil, sepet ve çerez tercihlerinizi hatırlamak için tarayıcı depolamasından yararlanır. Fiyatlar yalnızca TL gösterildiği sürece harici döviz kuru hizmetine istek gönderilmez. Önceki ziyaretlerden kalmış kur önbelleği tarayıcı verileri temizlenerek kaldırılabilir. ' : 'Site dil, sepet, çerez tercihleri ve döviz kuru önbelleği için tarayıcı depolamasından yararlanır. Döviz kuru Frankfurter hizmetinden alınır; bağlantı sırasında IP adresi gibi teknik bilgiler hizmete ulaşabilir. ') + 'Mevcut sitede reklam ve analitik izleme etkin değildir. Ayrıntılar ve tercih yönetimi için <a href="/cookies">Çerez Politikası</a> sayfasını inceleyebilirsiniz.'],
      ["07 · Saklama, güvenlik ve silme", "Kişisel veriler, işleme amacı için gerekli süre ve uygulanabilir yasal saklama yükümlülükleriyle sınırlı tutulur. Sipariş ve fatura kayıtlarında ilgili vergi, muhasebe ve tüketici mevzuatı; şikâyet ve uyuşmazlık kayıtlarında hakların kullanılması ve korunması için gerekli süreler esas alınır. İşleme şartları ortadan kalktığında silme, yok etme veya anonimleştirme hükümleri uygulanır. Güvenlik yaklaşımı; yetkisiz erişimin önlenmesini, erişimlerin görevle sınırlanmasını ve hesap bilgilerinin korunmasını kapsar. Site bağlantısı HTTPS ile şifrelenir. E-posta ile kart numaranızı, kart güvenlik kodunuzu veya hesap şifrenizi göndermeyin."],
      ["08 · Haklarınız ve başvuru", `KVKK 11 kapsamında kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse bilgi isteme, işleme amacını ve amaca uygun kullanımı öğrenme, yurt içinde veya yurt dışında aktarıldığı tarafları bilme, eksik veya yanlış verilerin düzeltilmesini isteme, kanuni şartları oluştuğunda silme veya yok etme talep etme, düzeltme ve silme işlemlerinin alıcılara bildirilmesini isteme, yalnızca otomatik analizle aleyhinize sonuç doğmasına itiraz etme ve hukuka aykırı işlemeden doğan zararın giderilmesini isteme haklarınız vardır. Başvurunuzu Barış Türkmen adına ${businessAddress} adresine yazılı olarak; <a href="mailto:baris.turkmen@hs01.kep.tr">baris.turkmen@hs01.kep.tr</a> adresine KEP yoluyla veya daha önce bize bildirdiğiniz ve sistemimizde kayıtlı e-posta adresinizi kullanarak ${privacy} adresine iletebilirsiniz. Başvuruda ad soyad, T.C. kimlik numarası (yabancılar için uyruğu, pasaport veya varsa kimlik numarası), tebligat adresi, varsa e-posta ve telefon, talep konusu ve yazılı başvuruda imza bulunmalıdır. İlgili bilgi ve belgeleri ekleyebilirsiniz. Başvurular niteliğine göre en kısa sürede ve en geç 30 gün içinde sonuçlandırılır; kural olarak ücretsizdir. Ek maliyet oluşursa yalnızca Kurulun belirlediği tarife uygulanabilir.`],
      ["09 · Politika güncellemeleri", "Hizmetlerin ve veri işleme süreçlerinin değişmesi halinde bu metin güncellenir. Güncel metin ve tarihi bu sayfada yayımlanır. Ayrı bir aydınlatma veya açık rıza gerektiren yeni faaliyetlerde bu yükümlülükler ayrıca yerine getirilmelidir."]
    ]
  }
};
